apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: preview-auth2
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: preview-auth
    helm:
    repoURL: registry.rnd.mendix.com/mx-platform/charts
    targetRevision: 0.2.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
