apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-config2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: studio
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-production.yaml
    path: helm-guestbook
    repoURL: https://github.com/indra0007/argocd-example-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
