apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace
  
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace1
  
  
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace2
